<?php

use Drupal\field\Entity\FieldStorageConfig;
use Drupal\field\Entity\FieldConfig;
use Drupal\Core\Field\FieldStorageDefinitionInterface;

/**
 * Implements hook_uninstall().
 */
function os2web_edoc_file_import_uninstall() {
  // Delete any content that may have been created for the custom node type.
  $nids_query = \Drupal::database()->select('node', 'n')
    ->fields('n', ['nid'])
    ->condition('n.type', ['esdh_case', 'esdh_document'], 'IN')
    ->execute();

  if ($nids = $nids_query->fetchCol()) {
    $storage = \Drupal::entityTypeManager()->getStorage('node');
    $entities = $storage->loadMultiple($nids);
    $storage->delete($entities);
    \Drupal::messenger()->addMessage(t('@number %type node(s) have been deleted.', [
      '@number' => count($nids),
      '%type' => 'scheduler_api_test',
    ]));
  }

  // Delete $esdh_case_fields configuration manually.
  $esdh_case_fields = ['field_case_documents', 'field_case_name', 'field_case_id', 'field_sagsnummer'];
  foreach ($esdh_case_fields as $field_name) {
    $field_config = FieldConfig::loadByName('node', 'esdh_case', $field_name);
    if ($field_config) {
      $field_config->delete();
    }

    $field_storage_config = FieldStorageConfig::loadByName('node', $field_name);
    if ($field_storage_config) {
      $field_storage_config->delete();
    }
  }

  // Delete $esdh_document_fields configuration manually.
  $esdh_document_fields = ['field_case_reference', 'field_document_id', 'field_document_title', 'field_case_file'];
  foreach ($esdh_document_fields as $field_name) {
    $field_config = FieldConfig::loadByName('node', 'esdh_document', $field_name);
    if ($field_config) {
      $field_config->delete();
    }

    $field_storage_config = FieldStorageConfig::loadByName('node', $field_name);
    if ($field_storage_config) {
      $field_storage_config->delete();
    }
  }

  foreach (['esdh_document', 'esdh_case'] as $nodeType) {
    // Delete content type.
    $content_type = \Drupal::entityTypeManager()
      ->getStorage('node_type')
      ->load($nodeType);
    $content_type->delete();
  }
}

/**
 * Implements hook_install().
 */
function os2web_edoc_file_import_install() {
//  os2web_edoc_file_import_add_case_fields();
//  os2web_edoc_file_import_add_document_fields();
}

/**
 * Adds fields to Case content type.
 */
function os2web_edoc_file_import_add_case_fields() {
  if (!FieldStorageConfig::loadByName('node', 'field_case_id')) {
    FieldStorageConfig::create([
      'field_name' => 'field_case_id',
      'entity_type' => 'node',
      'type' => 'string',
      'settings' => [
        'max_length' => 255,
        'is_ascii' => TRUE,
        'case_sensitive' => FALSE,
      ],
      'cardinality' => 1,
      'translatable' => FALSE,
    ])->save();

    FieldConfig::create([
      'field_storage' => FieldStorageConfig::loadByName('node', 'field_case_id'),
      'bundle' => 'esdh_case',
      'label' => 'Case ID',
      'required' => TRUE,
    ])->save();
  }

  if (!FieldStorageConfig::loadByName('node', 'field_case_name')) {
    FieldStorageConfig::create([
      'field_name' => 'field_case_name',
      'entity_type' => 'node',
      'type' => 'string',
      'settings' => [
        'max_length' => 255,
        'is_ascii' => TRUE,
        'case_sensitive' => FALSE,
      ],
      'cardinality' => 1,
      'translatable' => FALSE,
    ])->save();

    FieldConfig::create([
      'field_storage' => FieldStorageConfig::loadByName('node', 'field_case_name'),
      'bundle' => 'esdh_case',
      'label' => 'Case Name',
      'required' => TRUE,
    ])->save();
  }
}

/**
 * Adds fields to Document content type.
 */
function os2web_edoc_file_import_add_document_fields() {
  // Add Document ID field.
  if (!FieldStorageConfig::loadByName('node', 'field_document_id')) {
    FieldStorageConfig::create([
      'field_name' => 'field_document_id',
      'entity_type' => 'node',
      'type' => 'string',
      'settings' => [
        'max_length' => 255,
        'is_ascii' => TRUE,
        'case_sensitive' => FALSE,
      ],
      'cardinality' => 1,
      'translatable' => FALSE,
    ])->save();

    FieldConfig::create([
      'field_storage' => FieldStorageConfig::loadByName('node', 'field_document_id'),
      'bundle' => 'esdh_document',
      'label' => 'Document ID',
      'required' => TRUE,
    ])->save();
  }

  if (!FieldStorageConfig::loadByName('node', 'field_document_title')) {
    FieldStorageConfig::create([
      'field_name' => 'field_document_title',
      'entity_type' => 'node',
      'type' => 'string',
      'settings' => [
        'max_length' => 255,
        'is_ascii' => TRUE,
        'case_sensitive' => FALSE,
      ],
      'cardinality' => 1,
      'translatable' => FALSE,
    ])->save();

    FieldConfig::create([
      'field_storage' => FieldStorageConfig::loadByName('node', 'field_document_title'),
      'bundle' => 'esdh_document',
      'label' => 'Document Title',
      'required' => TRUE,
    ])->save();
  }

  if (!FieldStorageConfig::loadByName('node', 'field_case_reference')) {
    FieldStorageConfig::create([
      'field_name' => 'field_case_reference',
      'entity_type' => 'node',
      'type' => 'entity_reference',
      'settings' => [
        'target_type' => 'node',
        'handler' => 'default',
      ],
      'cardinality' => 1,
      'translatable' => FALSE,
    ])->save();

    FieldConfig::create([
      'field_storage' => FieldStorageConfig::loadByName('node', 'field_case_reference'),
      'bundle' => 'esdh_document',
      'label' => 'Case Reference',
      'required' => FALSE,
    ])->save();
  }
}
